# Configuration file to run tests on Travis-CI via GitHub notifications
# See https://travis-ci.org/

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - "pip install ."

script:
# Run the unit tests for nebulizer
  - "python setup.py test"

